### PR TITLE
port of #68 PR on jmDNS to latest code base

### PR DESCRIPTION
**Pull request by yfre**
porting the old PR with jmDNS enhancements to latest code base and updating jmDNS to latest stable version, which is 3.5.6

Signed-off-by: Eugen Freiter <freiter@gmx.de>

### CODE REVIEW

**Comment by yfre** [comment]
@ccutrer  i have ported your older PR to latest code base. i hope it is ok for you.

**Comment by ccutrer** [comment]
@J-N-K will this cause compatibility issues with OpenHAB? I know netty was/is an issue, and this is another package that OpenHAB also uses itself.

**Comment by gjvanderheiden** [comment]
OpenHab can always choose to exclude dependencies. Locally updated mdns and it runs with no issues. Same with netty. 
HAP-java also uses 

<dependency>
  <groupId>org.zeromq</groupId>
  <artifactId>curve25519-java</artifactId>
  <version>0.1.0</version>
</dependency>

which can be deleted with no issues.

If you can update the deps with no issues, openhab can use the old stone age stuff if they choose to do so. It will still be compatible.

Really dislike not updating because of  other projects. It's very well meant and carefull to OpenHab. But this way nobody moves.

**Comment by yfre** [comment]
just checked and openhab was upgraded to jmdns 3.5.6

https://github.com/openhab/openhab-core/pull/1721

i see this version also in my openhab3 setup

**Pull request merged**
