### PR TITLE
Upgrade bouncycastle dependencies to 1.72

### LINKED ISSUE #80: Support Bouncycastle's BC-Prov 1.60
HAP-Java is incompatible with Bouncycastle's BC-Prov dependency version 1.60.

While correctly specified in the `pom.xml` file, other dependencies in the same project can still cause a version bump, in my case it was Spring-Cloud Greenwich.SR1.
It updates the dependency to version 1.60 and then HAP-Java is raising the following, very confusing error during pairing:

```
org.bouncycastle.crypto.tls.TlsFatalAlert: bad_record_mac(20)
	at com.beowulfe.hap.impl.crypto.ChachaDecoder.decodeCiphertext(ChachaDecoder.java:31) ~[hap-1.1.5.jar:na]
	at com.beowulfe.hap.impl.crypto.ChachaDecoder.decodeCiphertext(ChachaDecoder.java:41) ~[hap-1.1.5.jar:na]
	at com.beowulfe.hap.impl.pairing.FinalPairHandler.decrypt(FinalPairHandler.java:44) ~[hap-1.1.5.jar:na]
	at com.beowulfe.hap.impl.pairing.FinalPairHandler.handle(FinalPairHandler.java:39) ~[hap-1.1.5.jar:na]
	at com.beowulfe.hap.impl.pairing.PairingManager.handle(PairingManager.java:59) ~[hap-1.1.5.jar:na]
	at com.beowulfe.hap.impl.connections.HttpSession.handlePairSetup(HttpSession.java:109) ~[hap-1.1.5.jar:na]
	at com.beowulfe.hap.impl.connections.HttpSession.handleRequest(HttpSession.java:53) ~[hap-1.1.5.jar:na]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.doHandleRequest(ConnectionImpl.java:54) ~[hap-1.1.5.jar:na]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.handleRequest(ConnectionImpl.java:47) ~[hap-1.1.5.jar:na]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:52) ~[hap-1.1.5.jar:na]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:17) ~[hap-1.1.5.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:350) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.34.Final.jar:4.1.34.Final]
	at java.base/java.lang.Thread.run(Thread.java:835) ~[na:na]
```

I'm not an expert in this area, but the following note one the [bouncycastle page](https://www.bouncycastle.org/latest_releases.html) looks promising:

> The PEM Parser now returns an X509TrustedCertificate block when parsing an openssl trusted certificate, the new object was required to allow the proper return of the trusted certificate's attribute block

I've now "fixed" it by enforcing version 1.51 like this, but it would, of course, break Spring Cloud, if it's using that particular part of the code. 

```kotlin
implementation("org.bouncycastle:bcprov-jdk15on:1.51") {
    isForce = true
}
```

A proper fix to support the latest version of bcprov would be nice, but until then it's at least documented and others can find it. Took me hours to finally figure this out and Google doesn't help in this case.

### PR DESCRIPTION
**Pull request by wborn**
Fixes #80
Succeeds #146

For release notes, see:

https://www.bouncycastle.org/releasenotes.html#r1rv72

# Pull Request Checklist

Please confirm that you've done the following when opening a new pull request:

  - [x] For fixes and other improvements, please reference the GitHub issue that your change addresses.
  - [x] For fixes, optimizations and new features, please add an entry to the CHANGES.md file.
  - [x] Run mvn compile before committing, so that the auto-code formatter will format your changes consistently with the rest of the project.

### CODE REVIEW

**Comment by wborn** [comment]
As Java 8 is targeted:

https://github.com/hap-java/HAP-Java/blob/781311e94c7967080119daec41d288a3a90b7691/pom.xml#L184-L185

the "jdk18on" artifacts can be used. :slightly_smiling_face:

**Comment by ccutrer** [comment]
If I apply this, then the HomeKit add-on won't load in OpenHAB 3.4.0-SNAPSHOT (as of last night), citing `Unresolved requirement: Import-Package: org.bouncycastle.tls; version="[1.72.0,2.0.0)"`. Is there a migration plan, or do all addons have to update to the new artifactid at the same time?

**Comment by wborn** [comment]
Thanks for having a look! Did you also build an add-on with the changes in https://github.com/openhab/openhab-addons/pull/11104? Those changes are required for embedding the bouncycastle 1.72 into the bundle.

**Comment by ccutrer** [comment]
I didn't see that PR. I now tried it. I can install the bundle, but logging reports `2022-10-14 13:57:55.948 [WARN ] [.server.impl.connections.HttpSession] - Unrecognized request for /characteristics` (which means it's using the unauthenticated servlet, instead of the authenticated one), and every accessory shows up as "No Response" on iOS.

**Comment by wborn** [comment]
That's unfortunate since I don't use HomeKit myself so I can't easily test or debug it. :slightly_frowning_face:

Do you have an idea what goes wrong? Is there some kind of HomeKit client that can be used for testing?

It would be helpful if there were unit tests for testing the crypto logic which would then fail with the upgraded dependencies. Then I could look into fixing those test. :slightly_smiling_face:

**Pull request closed without merging**
